version: '3.8'
services:
  mongo-6:
    image: mongo:6.0
    container_name: mongo-6
    ports:
      - '27017:27017'
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root.123456.
      MONGO_INITDB_DATABASE: test
      MONGO_USERNAME: test
      MONGO_PASSWORD: test.123456
    volumes:
      - /data/docker-data/mongo-6/data:/data/db
      - $PWD/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh