version: '3'
services:
  rabbitmq-3:
    container_name: rabbitmq-3
    image: rabbitmq:3.13.6-management
    cpus: '0.5'       # 限制使用 0.5 核 CPU
    mem_limit: 512M      # 限制使用 512M 内存
    restart: always
    hostname: rabbitmq-3
    ports:
      - 5672:5672
      - 15672:15672
    #    privileged: true
    volumes:
      - /data/docker-data/rabbitmq-3/log:/var/log/rabbitmq
      - $PWD/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /data/docker-data/rabbitmq-3/data:/var/lib/rabbitmq
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root.123456.

    networks:
      share-hobby-net:
        ipv4_address: "192.168.16.2"

networks:
  share-hobby-net:
    external: true