version: '3'
services:
  nacos-standalone:
    container_name: nacos-standalone
    image: nacos/nacos-server:v2.4.1
    cpus: '1.0'       # 限制使用 1 核 CPU
    mem_limit: 1G      # 限制使用 1GB 内存
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
#    privileged: true
    volumes:
      - /data/docker-data/nacos-standalone/log:/home/nacos/logs
    env_file:
      - ./env/standalone.env
    networks:
      - share-hobby-net

networks:
  share-hobby-net:
    external: true

