version: '3'
services:
  mysql-8:
    container_name: mysql-8
    image: mysql:8.4
    cpus: '0.5'       # 限制使用 0.5 核 CPU
    mem_limit: 512M      # 限制使用 512M 内存
    restart: always
    ports:
      - 5306:3306
#    privileged: true
    volumes:
      - /data/docker-data/mysql-8/log:/var/log/mysql
      - $PWD/my.cnf:/etc/mysql/my.cnf
      - /data/docker-data/mysql-8/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root.123456."
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci',
      '--max_connections=3000'
    ]
    networks:
      share-hobby-net:
        ipv4_address: "192.168.16.4"

networks:
  share-hobby-net:
    external: true

